### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ggrimbert** [shahabganji/aurelia-star-rate#1]
Hi, 

Can you provide some examples or documentation for us to try integrate this ?

**Comment by shahabganji** [comment]
Hi, yeah sure, just give me a day or two, cause I'm a bit busy on another project, thanks.
@ggrimbert

**Comment by shahabganji** [comment]
Hi @ggrimbert ,
I have added a sample in the README file, that's all you need, anyway if you think it's not fair and enough I would be so happy to hear and update as you wish
